### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by akirschbaum** [fge/grappa#25]
If a private rule is called during parser generation, the following exception is thrown:
```
Exception in thread "main" java.lang.RuntimeException: Error creating extended parser class: Rule method 'rule1'must not be private.
[...]
Caused by: org.parboiled.errors.GrammarException: Rule method 'rule1'must not be private.
Mark the method protected or package-private if you want to prevent public access!
	at org.parboiled.support.Checks.ensure(Checks.java:41)
	at org.parboiled.transform.ClassNodeInitializer.visitMethod(ClassNodeInitializer.java:187)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:911)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:97)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:97)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:66)
	at org.parboiled.Parboiled.createParser(Parboiled.java:67)
```

There should be a space in "[...]'rule1'must[...]".

**Comment by fge** [comment]
Which version is that?

Version 2.0.x has no Checks class.

**Comment by akirschbaum** [comment]
I believe this issue can be closed. My project did additionally include grappa-tracer-backport:2.0.0 which depends on grappa:1.0.4. My parser implementation was (incorrectly) using BasePaser from Grappa 1.0.4.

After having removed these outdated libraries, the error message now reads "`rule1(Var<Integer>) has private access in Parser`" which is correct.

**Comment by fge** [comment]
On request
